import type {
  AnalysisResult,
  ColumnSchema,
  Dialect,
  GeneratedSql,
  GeneratedTable,
  GenerationOptions,
  SqlValue,
  TableSchema,
} from "@/lib/types";

const INSERT_CHUNK_SIZE = 100;
const ROLLBACK_IN_CHUNK_SIZE = 300;
const ROLLBACK_PREDICATE_CHUNK_SIZE = 40;

export function renderSql(
  generatedTables: GeneratedTable[],
  analysis: AnalysisResult,
  options: GenerationOptions,
): Pick<GeneratedSql, "insertSql" | "rollbackSql" | "summary"> {
  const insertParts: string[] = [header("insert", analysis, options)];
  const rollbackParts: string[] = [header("rollback", analysis, options)];
  const cyclePreamble = renderCyclePreamble(options.dialect, analysis);
  const cyclePostamble = renderCyclePostamble(options.dialect, analysis);
  let insertStatements = 0;
  let rollbackStatements = 0;

  if (cyclePreamble) {
    insertParts.push(cyclePreamble);
    rollbackParts.push(cyclePreamble);
  }

  for (const generatedTable of generatedTables) {
    const chunks = chunk(generatedTable.rows, INSERT_CHUNK_SIZE);
    for (const rows of chunks) {
      insertParts.push(renderInsert(generatedTable.table, rows, options.dialect));
      insertStatements += 1;
    }
  }

  for (const generatedTable of [...generatedTables].reverse()) {
    const rendered = renderRollback(generatedTable.table, generatedTable.rows, options.dialect);
    rollbackParts.push(...rendered.sql);
    rollbackStatements += rendered.count;
  }

  if (cyclePostamble) {
    insertParts.push(cyclePostamble);
    rollbackParts.push(cyclePostamble);
  }

  return {
    insertSql: `${insertParts.filter(Boolean).join("\n\n")}\n`,
    rollbackSql: `${rollbackParts.filter(Boolean).join("\n\n")}\n`,
    summary: {
      tableCount: generatedTables.length,
      rowCountPerTable: options.rowCount,
      totalRows: generatedTables.reduce((sum, table) => sum + table.rows.length, 0),
      insertStatements,
      rollbackStatements,
    },
  };
}

function header(kind: "insert" | "rollback", analysis: AnalysisResult, options: GenerationOptions): string {
  const title = kind === "insert" ? "Seed INSERT SQL" : "Seed ROLLBACK SQL";
  const warnings = analysis.warnings.length > 0 ? analysis.warnings.map((warning) => `-- - ${warning}`).join("\n") : "-- - 없음";

  return [
    `-- ${title}`,
    "-- Generated by DDL Seed Generator",
    `-- Dialect: ${options.dialect}`,
    `-- Rows per table: ${options.rowCount}`,
    `-- Seed: ${options.seed}`,
    "-- Warnings:",
    warnings,
  ].join("\n");
}

function renderCyclePreamble(dialect: Dialect, analysis: AnalysisResult): string {
  if (analysis.cycleGroups.length === 0) {
    return "";
  }

  if (dialect === "mysql") {
    return ["SET FOREIGN_KEY_CHECKS = 0;"].join("\n");
  }

  if (dialect === "h2") {
    return ["SET REFERENTIAL_INTEGRITY FALSE;"].join("\n");
  }

  return [
    "-- PostgreSQL 순환 FK는 제약 조건이 DEFERRABLE일 때 SET CONSTRAINTS ALL DEFERRED로 처리됩니다.",
    "BEGIN;",
    "SET CONSTRAINTS ALL DEFERRED;",
  ].join("\n");
}

function renderCyclePostamble(dialect: Dialect, analysis: AnalysisResult): string {
  if (analysis.cycleGroups.length === 0) {
    return "";
  }

  if (dialect === "mysql") {
    return "SET FOREIGN_KEY_CHECKS = 1;";
  }

  if (dialect === "h2") {
    return "SET REFERENTIAL_INTEGRITY TRUE;";
  }

  return "COMMIT;";
}

function renderInsert(table: TableSchema, rows: Record<string, SqlValue>[], dialect: Dialect): string {
  const columns = table.columns.filter((c) => !c.computed);
  const needsOverride = dialect === "postgresql" && columns.some((c) => c.generatedAlwaysAsIdentity);
  const columnSql = columns.map((column) => quoteIdentifier(column.name, dialect)).join(", ");
  const valuesSql = rows
    .map((row) => `  (${columns.map((column) => renderValue(row[column.name], column, dialect)).join(", ")})`)
    .join(",\n");
  const overrideClause = needsOverride ? " OVERRIDING SYSTEM VALUE" : "";

  return `INSERT INTO ${quoteIdentifier(table.name, dialect)} (${columnSql})${overrideClause} VALUES\n${valuesSql};`;
}

function renderRollback(
  table: TableSchema,
  rows: Record<string, SqlValue>[],
  dialect: Dialect,
): { sql: string[]; count: number } {
  const keyColumns = rollbackKeyColumns(table);
  const keyHasNull = rows.some((row) => keyColumns.some((column) => row[column.name] === null));

  if (!keyHasNull && keyColumns.length === 1) {
    const column = keyColumns[0];
    return {
      sql: chunk(rows, ROLLBACK_IN_CHUNK_SIZE).map((rowChunk) => {
        const values = rowChunk.map((row) => renderValue(row[column.name], column, dialect)).join(", ");
        return `DELETE FROM ${quoteIdentifier(table.name, dialect)} WHERE ${quoteIdentifier(column.name, dialect)} IN (${values});`;
      }),
      count: Math.ceil(rows.length / ROLLBACK_IN_CHUNK_SIZE),
    };
  }

  if (!keyHasNull && keyColumns.length > 1) {
    return {
      sql: chunk(rows, ROLLBACK_IN_CHUNK_SIZE).map((rowChunk) => {
        const columns = keyColumns.map((column) => quoteIdentifier(column.name, dialect)).join(", ");
        const values = rowChunk
          .map((row) => `(${keyColumns.map((column) => renderValue(row[column.name], column, dialect)).join(", ")})`)
          .join(", ");
        return `DELETE FROM ${quoteIdentifier(table.name, dialect)} WHERE (${columns}) IN (${values});`;
      }),
      count: Math.ceil(rows.length / ROLLBACK_IN_CHUNK_SIZE),
    };
  }

  return {
    sql: chunk(rows, ROLLBACK_PREDICATE_CHUNK_SIZE).map((rowChunk) => {
      const predicates = rowChunk.map((row) => renderRowPredicate(keyColumns, row, dialect)).join("\n   OR ");
      return `DELETE FROM ${quoteIdentifier(table.name, dialect)} WHERE ${predicates};`;
    }),
    count: Math.ceil(rows.length / ROLLBACK_PREDICATE_CHUNK_SIZE),
  };
}

function rollbackKeyColumns(table: TableSchema): ColumnSchema[] {
  const primaryKeyColumns = table.primaryKey
    .map((name) => table.columns.find((column) => column.name.toLowerCase() === name.toLowerCase()))
    .filter((column): column is ColumnSchema => Boolean(column));

  if (primaryKeyColumns.length > 0) {
    return primaryKeyColumns;
  }

  const uniqueColumn = table.columns.find((column) => column.unique);
  if (uniqueColumn) {
    return [uniqueColumn];
  }

  return table.columns;
}

function renderRowPredicate(columns: ColumnSchema[], row: Record<string, SqlValue>, dialect: Dialect): string {
  return `(${columns
    .map((column) => {
      const value = row[column.name];
      if (value === null) {
        return `${quoteIdentifier(column.name, dialect)} IS NULL`;
      }
      return `${quoteIdentifier(column.name, dialect)} = ${renderValue(value, column, dialect)}`;
    })
    .join(" AND ")})`;
}

function renderValue(value: SqlValue, column: ColumnSchema, dialect: Dialect): string {
  if (value === null) {
    return "NULL";
  }

  if (typeof value === "boolean") {
    return dialect === "mysql" ? (value ? "1" : "0") : value ? "TRUE" : "FALSE";
  }

  if (typeof value === "number") {
    return Number.isFinite(value) ? String(value) : "0";
  }

  if (column.kind === "binary") {
    const hex = value.replace(/[^a-fA-F0-9]/g, "");
    if (dialect === "postgresql") {
      return `E'\\\\x${hex}'`;
    }
    return `X'${hex}'`;
  }

  const escaped = dialect === "mysql"
    ? value.replace(/\\/g, "\\\\").replace(/'/g, "''")
    : value.replace(/'/g, "''");
  return `'${escaped}'`;
}

function quoteIdentifier(identifier: string, dialect: Dialect): string {
  const quote = dialect === "mysql" ? "`" : "\"";
  const escapedQuote = dialect === "mysql" ? /`/g : /"/g;
  const replacement = quote + quote;

  return identifier
    .split(".")
    .map((part) => `${quote}${part.replace(escapedQuote, replacement)}${quote}`)
    .join(".");
}

function chunk<T>(items: T[], size: number): T[][] {
  const chunks: T[][] = [];
  for (let index = 0; index < items.length; index += size) {
    chunks.push(items.slice(index, index + size));
  }
  return chunks;
}
